### kulala-config

@api_prefix = /api/v1
@host = http://localhost:8000


### ping

GET {{host}} HTTP/1.1


### ListArticles

GET {{host}}{{api_prefix}}/articles?page=6 HTTP/1.1


### CreateArticles

POST {{host}}{{api_prefix}}/articles HTTP/1.1
Content-Type: application/json

{
  "author_id": 1,
  "content": "article1 content",
  "title": "article1"
}


### UpdateArticles

PATCH {{host}}{{api_prefix}}/articles/51 HTTP/1.1
Content-Type: application/json

{
  "title": "article-51"
}


### DeleteArticles

DELETE {{host}}{{api_prefix}}/articles/51 HTTP/1.1
