"""add telephone column for users

Revision ID: 0bfd89819bda
Revises: a595d92a6003
Create Date: 2025-12-25 05:41:35.464781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # add this line


# revision identifiers, used by Alembic.
revision: str = '0bfd89819bda'
down_revision: Union[str, Sequence[str], None] = 'a595d92a6003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telephone')
    # ### end Alembic commands ###
